# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "#research"
  weight = 20

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 40
  
[[main]]
  name = "Projects"
  url = "projects/"
  weight = 50
  identity = "Projects"

[[main]]
  name = "Photo Booth"
  url = "projects/#photo-booth"
  weight = 10
  parent = "Projects"
  
[[main]]
  name = "A Color Story"
  url = "projects/#a-color-story"
  weight = 20
  parent = "Projects"

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "cv/"
   weight = 60
   identifier = "CV"

[[main]]
   name = "Summary"
   url = "cv/#summary"
   weight = 10
   parent = "CV"
   
[[main]]
   name = "Experience"
   url = "cv/#work_exp"
   weight = 30
   parent = "CV"

[[main]]
   name = "Education"
   url = "cv/#education"
   weight = 20
   parent = "CV"
   
[[main]]
   name = "Honors"
   url = "cv/#awards"
   weight = 40
   parent = "CV"
   
[[main]]
   name = "Funding"
   url = "cv/#fellowships"
   weight = 50
   parent = "CV"
   
[[main]]
   name = "Service"
   url = "cv/#service"
   weight = 60
   parent = "CV"
 
[[main]]
   name = "Memberships"
   url = "cv/#memberships"
   weight = 70
   parent = "CV"
   
[[main]]
   name = "Teaching"
   url = "cv/#teaching"
   weight = 80
   parent = "CV"
   
[[main]]
   name = "Mentoring"
   url = "cv/#mentoring"
   weight = 90
   parent = "CV"
   
[[main]]
   name = "Trainings"
   url = "cv/#training"
   weight = 100
   parent = "CV"
